# Generated by Django 3.2.9 on 2021-11-06 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_schemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldWithRangeTemplate',
            fields=[
                ('fieldtemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_schemas.fieldtemplate')),
                ('min_value_range', models.BigIntegerField(verbose_name='Min value range')),
                ('max_value_range', models.BigIntegerField(verbose_name='Max value range')),
            ],
            options={
                'verbose_name': 'Field with range template',
                'verbose_name_plural': 'Field with range templates',
            },
            bases=('data_schemas.fieldtemplate',),
        ),
        migrations.CreateModel(
            name='IntegerField',
            fields=[
                ('fieldwithrangetemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_schemas.fieldwithrangetemplate')),
            ],
            options={
                'verbose_name': 'Integer field',
                'verbose_name_plural': 'Integer fields',
            },
            bases=('data_schemas.fieldwithrangetemplate',),
        ),
    ]
