# Generated by Django 3.2.9 on 2021-11-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_schemas', '0002_fieldwithrangetemplate_integerfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataschema',
            name='rows_counter',
            field=models.BigIntegerField(default=None, verbose_name='Raws counter'),
        ),
    ]
