# Generated by Django 3.2.9 on 2021-11-06 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_schemas', '0003_alter_dataschema_rows_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateField',
            fields=[
                ('fieldtemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_schemas.fieldtemplate')),
            ],
            options={
                'verbose_name': 'Date field',
                'verbose_name_plural': 'Date fields',
            },
            bases=('data_schemas.fieldtemplate',),
        ),
    ]
