# Generated by Django 3.2.9 on 2021-11-08 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_schemas', '0005_rename_dataschema_csvdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvdata',
            options={'verbose_name': 'CSV Data', 'verbose_name_plural': 'CSV Data'},
        ),
        migrations.AlterField(
            model_name='fieldtemplate',
            name='schema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_schemas.schema', verbose_name='Schema'),
            preserve_default=False,
        ),
    ]
