# Generated by Django 3.2.9 on 2021-11-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_schemas', '0007_rename_csvdata_dataset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'verbose_name': 'Dataset', 'verbose_name_plural': 'Dataset'},
        ),
        migrations.AlterField(
            model_name='schema',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Title'),
        ),
    ]
